<section id="works-container">
    <section id="list-mode">
        <a class="pure-button button-small button-secondary" href="<?php echo $this->url(array('controller' => 'travaux', 'action' => 'liste', 'mode' => 'prios')) ?>"><i class="fa fa-exclamation-triangle"></i> Priorités</a>
        <a class="pure-button button-small button-secondary pure-button-active" href="<?php echo $this->url(array('controller' => 'travaux', 'action' => 'liste', 'mode' => 'types')) ?>"><i class="fa fa-ellipsis-v"></i> Types</a>
    </section>
    <section id="works-list">
    <?php foreach ($this->works['types'] as $currentType) : ?>
        <?php if (!empty($currentType['priosWorks'])) : ?>
        <p class="type-big"><?php echo $currentType['label_type'] ?></p>
            <?php foreach ($currentType['priosWorks'] as $currentPrioWorks): ?>
                <div class="prio-small prio-<?php echo $currentPrioWorks['prio_id']  ?>">
                <span class="prio-name"><?php echo $currentPrioWorks['prio_label'] ?></span>
                
                <ul>
                    <?php foreach ($currentPrioWorks['works'] as $currentWork) : ?>
                    <li data-workid="<?php echo $currentWork['id'] ?>"<?php if(isset($currentWork['added'])): ?> class="added"<?php endif; ?>>
                        <?php if(isset($currentWork['cur_user'])): ?>
                        <span class="in-cur-user-list"><i class="fa fa-thumb-tack"></i></span>
                        <?php endif; ?>
                        <div class="title">
                            <?php echo $currentWork['title'] ?>
                        </div>
                        <div class="location">
                            <?php if(!empty($currentWork['oeuvre_title'])) : echo $currentWork['oeuvre_numero'] . ' - ' . $currentWork['oeuvre_title']; elseif(!empty($currentWork['coords_x'])): echo $currentWork['coords_x'] . ', ' . $currentWork['coords_y']; endif; ?>
                        </div>
                        <div class="work-options">
                            <?php if ($this->changeWorkPrio) : echo ' ' . $this->ChangePrioButtons($currentWork['id'], $currentPrioWorks['prio_id']); endif; ?>
                            <?php if ($this->setWorkDone && $currentPrioWorks['prio_id'] != $this->workDonePrio) : echo ' ' . $this->SetWorkDoneButton($currentWork['id']); endif; ?>
                            <?php if ($this->removeWork) : echo ' ' . $this->RemoveWorkButton($currentWork['id']); endif; ?>
                            <?php if (isset($this->addWorkToUserList) && $this->addWorkToUserList && !isset($currentWork['added']) && Application_Model_Travaux::$PRIORITIES['Déjà effectué'] != $currentPrioId) : echo ' ' . $this->AddWorkToUserListButton($currentWork['id'], Zend_Auth::getInstance()->getIdentity()->id); endif; ?>
                        </div>
                    </li>
                        
                        <?php /*
                        <li>
                            <?php echo $currentWork['id'] ?> : <?php echo $currentWork['title'] ?><?php if ($this->changeWorkPrio) : echo ' ' . $this->ChangePrioButtons($currentWork['id'], $currentPrioWorks['prio_id']);
                endif; ?>
                            <?php if ($this->setWorkDone && $currentPrioWorks['prio_id'] != $this->workDonePrio) : echo ' ' . $this->SetWorkDoneButton($currentWork['id']);
                            endif; ?>
                        <?php if ($this->removeWork) : echo ' ' . $this->RemoveWorkButton($currentWork['id']);
                        endif; ?>
                        </li>
                        
                        */ ?>
                <?php endforeach; ?>
                </ul>
                </div>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach; ?>
    </section>
    <section id="middle">
    </section>
    <?php $paths = $this->getScriptPaths(); require_once $paths[0] . '/travaux/work-view.phtml' ?>
</section>