<section id="sidebar">
    <div id="stats_container" class="ui message">
        <h3>Statistiques</h3>
        Travaux urgents : <span id="urgent_count"></span></br>
        Moins de 10 jours restant : <span id="ten_days_or_less_count"></span></br>
        Travaux en retard : <span id="late_count"></span></br>
        Affectation des travaux urgents : <span id="affectation_ratio_urgent"></span> %</br>
        Affectation de l'ensemble : <span id="affectation_ratio"></span> %</br>
    </div>
</section>
<section id="content" class="liste_perso">
    <?php foreach ($this->works['prios'] as $currentPrioId => $currentPrio): ?>
        <?php if (count($currentPrio['typesWorks'])) : ?>
            <span class="prio<?php if($currentPrioId == Application_Model_Travaux::$PRIORITIES['Important']) echo ' urgent'; ?>"><?php echo $currentPrio['label_prio'] ?></span><br/><br/>
            <?php foreach ($currentPrio['typesWorks'] as $currentType): ?>
                <?php if (isset($currentType['type'])) : ?>
                    <div class="ui label" style="background-color:#<?php echo $currentType['type']['color'] ?>">
                        <?php echo $currentType['type']['name'] ?>
                    </div>
                <?php else : ?>
                    <?php echo $this->noTypeLabel ?>
                <?php endif ?>
                <table class="ui table works_table">
                    <tbody>
                        <?php foreach ($currentType['works'] as $currentWork) : ?>
                            <tr data-workid="<?php echo $currentWork['id'] ?>">
                                    <?php
                                    echo '</td><td class="work_title">';                                    
                                    if (!empty($currentWork['title'])) {
                                        echo '<span class="title">' . $currentWork['title'] . '</span>';
                                    } else {
                                        echo '<span class="title">' . Application_Model_Travaux::$UNTITLED_WORK . '</span>';
                                    }
                                    if (!empty($currentWork['oeuvre_numero'])) {
                                        echo ' <span class="ui label w_oeuvre">#' . $currentWork['oeuvre_numero'] . ' - ' . $currentWork['oeuvre_title'] . '</span> ';
                                    }
                                    echo '</td>';
                                    ?>
                                <td class="options">
                                    <div class="small icon ui buttons">
                                        <?php echo $this->SetWorkDoneButton(); ?>
                                        <?php echo $this->RemoveWorkFromUserListButton(); ?>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endforeach; ?>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php echo $this->partial('modals.phtml'); ?>
    <?php echo $this->partial('travaux/work-view.phtml', array('roleId' => $this->roleId)); ?>
</section>

<?php goto end; ?>
<section id="works-container">
    <section id="works-list">
        <?php foreach ($this->works['prios'] as $currentPrioId => $currentPrio): ?>
            <?php if (count($currentPrio['typesWorks'])) : ?>
                <div class="prio prio-<?php echo $currentPrioId ?>">
                    <span class="prio-name"><?php echo $currentPrio['label_prio'] ?></span>
                    <?php foreach ($currentPrio['typesWorks'] as $currentType): ?>
                        <?php if (isset($currentType['type'])) : ?>
                            <p class="type"><?php echo $currentType['type']['name'] ?></p>
                        <?php else : ?>
                            <p class="type"><?php echo $this->noTypeLabel ?></p>
                        <?php endif ?>
                        <ul>
                            <?php foreach ($currentType['works'] as $currentWork) : ?>
                                <li data-workid="<?php echo $currentWork['id'] ?>"<?php if (isset($currentWork['added'])): ?> class="added"<?php endif; ?>>
                                    <?php if (isset($currentWork['cur_user'])): ?>
                                        <span class="in-cur-user-list"><i class="fa fa-thumb-tack"></i></span>
                                    <?php endif; ?>
                                    <div class="title">
                                        <?php echo $currentWork['title'] ?>
                                    </div>
                                    <div class="location">
                                        <?php
                                        if (!empty($currentWork['oeuvre_title'])) : echo $currentWork['oeuvre_numero'] . ' - ' . $currentWork['oeuvre_title'];
                                        elseif (!empty($currentWork['coords_x'])): echo $currentWork['coords_x'] . ', ' . $currentWork['coords_y'];
                                        endif;
                                        ?>
                                    </div>
                                    <div class="work-options">
                                        <?php if (isset($this->setWorkDone) && $this->setWorkDone && $currentPrioId != $this->workDonePrio) : echo ' ' . $this->SetWorkDoneButton($currentWork['id']);
                                        endif;
                                        ?>
                                <?php if (isset($this->removeWorkFromList) && $this->removeWorkFromList) : echo ' ' . $this->RemoveWorkFromUserListButton($currentWork['id'], Zend_Auth::getInstance()->getIdentity()->id);
                                endif;
                                ?>
                                    </div>
                                </li>
                    <?php endforeach ?>
                        </ul>
        <?php endforeach; ?>
                </div>
        <?php endif; ?>
    <?php endforeach; ?>
    </section>
    <section id="middle">
    </section>
<?php echo $this->partial('travaux/modals.phtml'); ?>
<?php echo $this->partial('travaux/work-view.phtml'); ?>
</section>
<?php end: ?>