<section id="sidebar">
    <h3>Statistiques</h3>
    Travaux urgents : <span id="urgent_count"><?php echo $this->worksStats['urgent_works'] ?></span></br>
    Moins de 10 jours restant : <span id="ten_days_or_less_count"><?php echo $this->worksStats['ten_days_or_less_works'] ?></span></br>
    Travaux en retard : <span id="late_count"><?php echo $this->worksStats['late_works'] ?></span></br>
    Affectation des travaux urgents : <span id="affectation_ratio_urgent"><?php echo $this->worksStats['affectation_ratio_urgent'] ?></span> %</br>
    Affectation de l'ensemble : <span id="affectation_ratio"><?php echo $this->worksStats['affectation_ratio'] ?></span> %</br>
</section>
<section id="content">

    <?php foreach ($this->works['prios'] as $currentPrioId => $currentPrio): 
        $curUserId = Zend_Auth::getInstance()->getIdentity()->id; ?>
        <?php echo $currentPrio['label_prio'] ?>
        <table class="ui table works_table" id="works_<?php echo $currentPrioId ?>">
            <tbody>
                <?php foreach ($currentPrio['works'] as $workId => $curWork): ?>
                    <tr data-workid="<?php echo $workId; ?>"<?php
                    /*if(!empty($curWork['user_id'])) {
                        echo ' title="';
                        $this->PrintInUserListMessage($curUserId, $curWork['user_id'], $curWork['user_fname'], $curWork['user_lname']);
                        echo '"';
                    } */?>
                        data-workstate="<?php
                        if(!empty($curWork['user_id'])) : 
                            if($curUserId == $curWork['user_id'])
                                echo 'current';
                            else
                                echo 'other';
                        else :
                            echo 'free';
                        endif;
?>">
                        <td class="item">
                            <?php 
                            // Icons display : site.js
                            echo '<i class="ui icon pin"></i>';
                            echo '<i class="ui icon lock"></i>';
                            if (!empty($curWork['types']) && count($curWork['types'])) {
                                foreach ($curWork['types'] as $typeId => $typeAr) :
                                    echo '<div class="ui label" style="background-color:#' . $typeAr['color'] . '">' . $typeAr['name'] . '</div>';
                                endforeach;
                            }
                            if(isset($curWork['days_to'])) {
                                $daysTo = (int)$curWork['days_to'];
                                $class;
                                if($daysTo <= 3) {
                                    $class="days_to urgent";
                                } else {
                                    $class="days_to";
                                }
                                if($daysTo > 0) {
                                    $daysTo = 'J - ' . abs($daysTo);
                                } elseif($daysTo == 0) {
                                    $daysTo = 'Aujourd\'hui !';
                                } else {
                                    $daysTo = abs($daysTo) . ' jours en retard';
                                }
                                
                                echo '<span class="' . $class . '">' . $daysTo . '</span>';
                            }
                            if (!empty($curWork['title'])) {
                                echo '<span class="work_title"> ' . $curWork['title'] . '</span>';
                            } else if (!empty($curWork['oeuvre_numero'])) {
                                echo '<span class="work_title"> ' . '#' . $curWork['oeuvre_numero'] . ' - ' . $curWork['oeuvre_title'] . '</span>';
                            } else {
                                echo '<span class="work_title"> ' . Application_Model_Travaux::$UNTITLED_WORK . '</span>';
                            }
                            ?>
                            </td>
                        <td class="options">
                            <div class="tiny icon ui buttons">
                                <?php if (isset($this->changeWorkPrio) && $this->changeWorkPrio) : echo $this->ChangePrioButtons($currentPrioId); endif; ?>
                                <?php if (isset($this->setWorkDone) && $this->setWorkDone) : echo $this->SetWorkDoneButton($workId); endif; ?>
                                <?php if (isset($this->removeWork) && $this->removeWork) : echo $this->RemoveWorkButton($workId); endif; ?>
                                <?php if (isset($this->editWork) && $this->editWork) : echo $this->EditWorkButton($workId); endif; ?>
                                <?php
                                $alreadyDoneCode = Application_Model_Travaux::$PRIORITIES['Déjà effectué'];
                                if (isset($this->addWorkToUserList) && $this->addWorkToUserList && $alreadyDoneCode != $currentPrioId) {
                                    if(!isset($curWork['added'])) {             // Personne ne l'a ajouté
                                    } else if(isset($curWork['cur_user'])) {    // C'est l'utilisateur courant qui l'a ajouté
                                    }
                                    echo $this->AddWorkToUserListButton();
                                    echo $this->RemoveWorkFromUserListButton();
                                }
                                ?>
                            </div>
                        </td>
                    </tr>
    <?php endforeach; ?>
            </tbody>
        </table>
        <?php endforeach; ?>
    <?php echo $this->partial('modals.phtml'); ?>
    <?php echo $this->partial('travaux/work-view.phtml', array('roleId' => $this->roleId)); ?>
</section>

            <?php goto end; ?>
<section id="works-container">
    <section id="works-list">
            <?php foreach ($this->works['prios'] as $currentPrioId => $currentPrio): ?>
            <div class="prio prio-<?php echo $currentPrioId ?>">
                <span class="prio-name"><?php echo $currentPrio['label_prio'] ?></span>
                <?php foreach ($currentPrio['typesWorks'] as $currentType): ?>
                        <?php if (isset($currentType['type'])) : ?>
                        <p class="type"><?php echo $currentType['type']['name'] ?></p>
                            <?php else : ?>
                        <p class="type"><?php echo $this->noTypeLabel ?></p>
                            <?php endif ?>
                    <ul>
                                <?php foreach ($currentType['works'] as $currentWork) : ?>
                            <li data-workid="<?php echo $currentWork['id'] ?>"<?php if (isset($currentWork['added'])): ?> class="added"<?php endif; ?>>
            <?php if (isset($currentWork['cur_user'])): ?>
                                    <span class="in-cur-user-list"><i class="fa fa-thumb-tack"></i></span>
                                    <?php endif; ?>
                                <div class="title">
                                    <?php echo $currentWork['title'] ?>
                                </div>
                                <div class="location">
            <?php
            if (!empty($currentWork['oeuvre_title'])) : echo $currentWork['oeuvre_numero'] . ' - ' . $currentWork['oeuvre_title'];
            elseif (!empty($currentWork['coords_x'])): echo $currentWork['coords_x'] . ', ' . $currentWork['coords_y'];
            endif;
            ?>
                                </div>
                                <div class="work-options">
                                    <?php
                                    if (isset($this->changeWorkPrio) && $this->changeWorkPrio) : echo ' ' . $this->ChangePrioButtons($currentWork['id'], $currentPrioId);
                                    endif;
                                    ?>
                                    <?php
                                    if (isset($this->setWorkDone) && $this->setWorkDone && $currentPrioId != $this->workDonePrio) : echo ' ' . $this->SetWorkDoneButton($currentWork['id']);
                                    endif;
                                    ?>
                            <?php
                            if (isset($this->removeWork) && $this->removeWork) : echo ' ' . $this->RemoveWorkButton($currentWork['id']);
                            endif;
                            ?>
                    <?php
                    if (isset($this->addWorkToUserList) && $this->addWorkToUserList && !isset($currentWork['added']) && Application_Model_Travaux::$PRIORITIES['Déjà effectué'] != $currentPrioId) : echo ' ' . $this->AddWorkToUserListButton($currentWork['id'], Zend_Auth::getInstance()->getIdentity()->id);
                    endif;
                    ?>
                                </div>
                            </li>
            <?php endforeach ?>
                    </ul>
    <?php endforeach; ?>
            </div>
<?php endforeach; ?>
    </section>
    <section id="middle">
    </section>
<?php
$paths = $this->getScriptPaths();
require_once $paths[0] . '/travaux/work-view.phtml'
?>
</section>
<?php end: ?>