<section id="works-container">
    <section id="works-list">
        <?php foreach ($this->works['prios'] as $currentPrioId => $currentPrio): ?>
            <?php if(count($currentPrio['typesWorks'])) : ?>
            <div class="prio prio-<?php echo $currentPrioId ?>">
                <span class="prio-name"><?php echo $currentPrio['label_prio'] ?></span>
                <?php foreach ($currentPrio['typesWorks'] as $currentType): ?>
                    <?php if (isset($currentType['type'])) : ?>
                        <p class="type"><?php echo $currentType['type']['name'] ?></p>
                    <?php else : ?>
                        <p class="type"><?php echo $this->noTypeLabel ?></p>
                    <?php endif ?>
                    <ul>
                        <?php foreach ($currentType['works'] as $currentWork) : ?>
                            <li data-workid="<?php echo $currentWork['id'] ?>"<?php if(isset($currentWork['added'])): ?> class="added"<?php endif; ?>>
                                <?php if(isset($currentWork['cur_user'])): ?>
                                <span class="in-cur-user-list"><i class="fa fa-thumb-tack"></i></span>
                                <?php endif; ?>
                                <div class="title">
                                    <?php echo $currentWork['title'] ?>
                                </div>
                                <div class="location">
                                    <?php if(!empty($currentWork['oeuvre_title'])) : echo $currentWork['oeuvre_numero'] . ' - ' . $currentWork['oeuvre_title']; elseif(!empty($currentWork['coords_x'])): echo $currentWork['coords_x'] . ', ' . $currentWork['coords_y']; endif; ?>
                                </div>
                                <div class="work-options">
                                    <?php if (isset($this->setWorkDone) && $this->setWorkDone && $currentPrioId != $this->workDonePrio) : echo ' ' . $this->SetWorkDoneButton($currentWork['id']); endif; ?>
                                    <?php if (isset($this->removeWorkFromList) && $this->removeWorkFromList) : echo ' ' . $this->RemoveWorkFromListButton($currentWork['id'], Zend_Auth::getInstance()->getIdentity()->id); endif; ?>
                                </div>
                            </li>
                <?php endforeach ?>
                    </ul>
        <?php endforeach; ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
    </section>
    <section id="middle">
    </section>
    <?php $paths = $this->getScriptPaths(); require_once $paths[0] . '/travaux/work-view.phtml' ?>
</section>