<?php
    $f = $this->element;
?>
<form class="<?php echo $f->getAttrib('class') ?>"
      id="<?php echo $f->getAttrib('id') ?>"
      action="<?php echo $f->getAction() ?>"
      method="<?php echo $f->getMethod() ?>">
    <h2 class="ui dividing header"><?php echo $f->form_title->render() ?></h2>
    <div class="field"><?php echo $f->fname->render(); ?></div>
    <div class="field"><?php echo $f->lname->render(); ?></div>
    <div class="field"><?php echo $f->pass->render(); ?></div>
    <div class="field"><?php echo $f->mail->render(); ?></div>
    <?php if(isset($f->role)) : ?>
    <div class="field"><?php echo $f->role->render(); ?></div>
	<?php endif; ?>
    <div class="ui hidden divider"></div>
    <div class="ui big fluid primary button" id="edit_user">
        Modifier les paramètres
    </div>
</form>