<div class="ui small modal" id="delete_work_modal">
    <i class="close icon"></i>
    <div class="header">
        Supprimer un travail
    </div>
    <div class="content">
        <div class="description">
            Voulez-vous supprimer le travail sélectionné ?
        </div>
    </div>
    <div class="actions">
        <div class="ui button negative">Annuler</div>
        <div class="ui button positive">OK</div>
    </div>
</div>
<div class="ui small modal" id="delete_user_modal">
    <i class="close icon"></i>
    <div class="header">
        Supprimer un utilisateur
    </div>
    <div class="content">
        <div class="description">
            Voulez-vous supprimer l'utilisateur sélectionné ?
        </div>
    </div>
    <div class="actions">
        <div class="ui button negative">Annuler</div>
        <div class="ui button positive">OK</div>
    </div>
</div>
<div class="ui small modal" id="set_work_done_modal">
    <i class="close icon"></i>
    <div class="header">
        Marquer un travail comme fait
    </div>
    <div class="content">
        <div class="description">
            Voulez-vous marquer le travail comme effectué ?
        </div>
    </div>
    <div class="actions">
        <div class="ui button negative">Annuler</div>
        <div class="ui button positive">OK</div>
    </div>
</div>