<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
    <head>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle($this->title) ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->jQuery() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body<?php if(isset($this->err)) echo ' class="error"' ?>>
        <div id="content">
            <div class="ui menu green" id="mainMenu">
                <div class="header item">
                    VDF Works
                </div>
                <?php if(isset($this->mainMenuTemplateFile)) echo $this->partial($this->mainMenuTemplateFile, array('page' => $this->page)); ?>
                <div class="right menu">
                <?php if(isset($this->page) && $this->page == 'list-works') : ?>
                    <?php echo $this->partial('travaux/liste-options.phtml', array('viewMode' => $this->viewMode)); ?>
                <?php endif; ?>
                <?php if(isset($this->lname) && isset($this->fname)) : ?>
                <?php echo $this->GetUserTile($this->uid, $this->fname, $this->lname, $this->roleName); ?>
                <?php endif; ?>
                </div>
              </div>
            <div id="noticesContainer"><?php if(isset($this->noticeTemplate)) : echo $this->partial($this->noticeTemplate); endif; ?></div>
            <section id="container">
                <?php echo $this->layout()->content ?>
            </section>
        </div>
        <input type="hidden" id="waiting_action" />
    </body>
</html>