<a href="<?php echo $this->url(array('controller' => 'travaux', 'action' => 'liste'), null, true) ?>"
   class="item<?php if(isset($this->page) && 'list' == $this->page) : echo ' active'; endif; ?>">
    <i class="list icon"></i> Travaux
</a>
<a href="<?php echo $this->url(array('controller' => 'travaux', 'action' => 'ajouter'), null, true) ?>"
   class="item<?php if(isset($this->page) && 'add-work' == $this->page) : echo ' active'; endif; ?>">
    <i class="plus icon"></i> Ajouter
</a>
<a href="<?php echo $this->url(array('controller' => 'type', 'action' => 'liste'), null, true) ?>"
   class="item<?php if(isset($this->page) && 'type-list' == $this->page) : echo ' active'; endif; ?>">
    <i class="tag icon"></i> Types
</a>
<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'liste'), null, true) ?>"
   class="item<?php if(isset($this->page) && 'users-list' == $this->page) : echo ' active'; endif; ?>">
    <i class="user icon"></i> Utilisateurs
</a>
<a href="<?php echo $this->url(array('controller' => 'oeuvre', 'action' => 'liste'), null, true) ?>"
   class="item<?php if(isset($this->page) && 'oeuvre-list' == $this->page) : echo ' active'; endif; ?>">
    <i class="marker icon"></i> Oeuvres
</a>